'use client';

import { useEffect, useState } from 'react';
import LayoutWrapper from '@/components/layout-wrapper';
import Heatmap from '@/components/heatmap';
import { useStore } from '@/store/useStore';
import {
  FileSpreadsheet,
  Printer,
  Download,
  Activity,
  TrendingUp,
  ClipboardList,
  RotateCw,
  AlertTriangle,
  Flame,
  BookOpen,
  CheckCircle,
  Calendar,
  Loader2,
  GraduationCap
} from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export default function ReportsPage() {
  const { stats, fetchDashboardData, isLoading } = useStore();
  const [analyticsData, setAnalyticsData] = useState<any | null>(null);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    fetchDashboardData();

    fetch('/api/analytics')
      .then(res => res.json())
      .then(data => setAnalyticsData(data))
      .catch(() => {});
  }, [fetchDashboardData]);

  const handlePrint = () => {
    window.print();
  };

  if (!isMounted) return null;

  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <LayoutWrapper
      title="Academic Performance Report"
      subtitle="High-density study report with analytics charts, consistency data, and subject breakdowns."
    >
      <div className="space-y-6">
        
        {/* Action Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 bg-surface border border-border p-4 rounded-2xl shadow-sm print:hidden">
          <div className="flex items-center space-x-2">
            <FileSpreadsheet className="w-5 h-5 text-primary" />
            <div>
              <h3 className="font-hanken font-bold text-sm text-slate-800">Study Performance Report</h3>
              <p className="text-slate-400 text-xs font-semibold">Generated: {todayFormatted}</p>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-primary hover:bg-primary-dark text-white rounded-xl text-xs font-bold flex items-center space-x-1.5 shadow-sm transition-all"
            >
              <Printer className="w-4 h-4" />
              <span>Print Report</span>
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="space-y-8 print:space-y-6" id="report-content">
          
          {/* Report Header (visible on print) */}
          <div className="hidden print:block border-b-2 border-primary pb-4 mb-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <GraduationCap className="w-8 h-8 text-primary" />
                <div>
                  <h1 className="font-hanken font-bold text-2xl text-primary">StudyPulse</h1>
                  <p className="text-xs text-slate-500 font-semibold">ICSE Class 10 • Academic Performance Report</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-slate-600">{todayFormatted}</p>
                <p className="text-[10px] text-slate-400 font-semibold">Auto-generated by StudyPulse Analytics Engine</p>
              </div>
            </div>
          </div>

          {/* Section 1: Key Performance Indicators */}
          <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200">
            <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
              <Activity className="w-5 h-5 text-primary" />
              <span>Key Performance Indicators</span>
            </h3>

            {isLoading && !stats ? (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="w-6 h-6 animate-spin text-primary" />
              </div>
            ) : (
              <div className="grid grid-cols-2 md:grid-cols-5 gap-4 print:grid-cols-5">
                {[
                  { label: 'Reliability Score', value: `${stats?.reliabilityScore ?? 0}/100`, icon: Activity, accent: 'text-primary' },
                  { label: 'Study Consistency', value: `${stats?.studyConsistency ?? 0}%`, icon: Flame, accent: 'text-success' },
                  { label: 'Homework Pending', value: stats?.homeworkPending ?? 0, icon: ClipboardList, accent: 'text-primary' },
                  { label: 'Revision Due', value: stats?.revisionDue ?? 0, icon: RotateCw, accent: 'text-warning' },
                  { label: 'Missed Tasks', value: stats?.missedTasks ?? 0, icon: AlertTriangle, accent: 'text-critical' },
                ].map((kpi, i) => {
                  const Icon = kpi.icon;
                  return (
                    <div key={i} className="border border-slate-100 rounded-xl p-4 bg-slate-50/30 print:bg-white print:border-slate-200">
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-[9px] font-black uppercase tracking-wider text-slate-400">{kpi.label}</span>
                        <Icon className={`w-4 h-4 ${kpi.accent}`} />
                      </div>
                      <span className="text-xl font-black font-hanken text-slate-800">{kpi.value}</span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Section 2: Detailed Analytics Breakdown */}
          {analyticsData && (
            <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200">
              <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
                <TrendingUp className="w-5 h-5 text-primary" />
                <span>Completion Rate Breakdown</span>
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-4 gap-4 print:grid-cols-4">
                {[
                  { label: 'Homework Completion', value: `${analyticsData.homeworkCompletionRate}%`, color: 'bg-primary' },
                  { label: 'Revision Completion', value: `${analyticsData.revisionCompletionRate}%`, color: 'bg-success' },
                  { label: 'Study Consistency', value: `${analyticsData.consistencyRate}%`, color: 'bg-warning' },
                  { label: 'Backlog Index', value: `${analyticsData.backlogScore}/100`, color: analyticsData.backlogScore > 30 ? 'bg-critical' : 'bg-success' },
                ].map((metric, i) => (
                  <div key={i} className="border border-slate-100 rounded-xl p-4 bg-slate-50/30 print:bg-white">
                    <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 block mb-2">{metric.label}</span>
                    <span className="text-2xl font-black font-hanken text-slate-800">{metric.value}</span>
                    <div className="mt-3 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${metric.color} transition-all duration-500`}
                        style={{ width: `${parseInt(metric.value)}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 3: Weekly Study Trend Chart */}
          <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200 print:break-before-page">
            <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
              <BookOpen className="w-5 h-5 text-primary" />
              <span>Weekly Tuition Duration (Last 7 Days)</span>
            </h3>

            <div className="h-[240px] print:h-[200px]">
              {stats?.weeklyTrend && stats.weeklyTrend.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={stats.weeklyTrend} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <XAxis dataKey="date" stroke="#94a3b8" fontSize={10} fontWeight="bold" tickLine={false} />
                    <YAxis stroke="#94a3b8" fontSize={10} fontWeight="bold" tickLine={false} />
                    <Tooltip
                      contentStyle={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '11px' }}
                    />
                    <Bar dataKey="duration" fill="#1a4595" radius={[4, 4, 0, 0]} barSize={32} name="Minutes" />
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-full flex items-center justify-center text-xs font-semibold text-slate-400">
                  No tuition data to display for the weekly trend.
                </div>
              )}
            </div>
          </div>

          {/* Section 4: Revision Completion by Subject */}
          {analyticsData?.revisionConsistencyChart && analyticsData.revisionConsistencyChart.length > 0 && (
            <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200">
              <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
                <RotateCw className="w-5 h-5 text-primary" />
                <span>Spaced Revision Rates by Subject</span>
              </h3>

              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-3 px-4 font-black uppercase text-slate-500 tracking-wider text-[10px]">Subject</th>
                      <th className="text-center py-3 px-4 font-black uppercase text-slate-500 tracking-wider text-[10px]">Scheduled</th>
                      <th className="text-center py-3 px-4 font-black uppercase text-slate-500 tracking-wider text-[10px]">Completed</th>
                      <th className="text-center py-3 px-4 font-black uppercase text-slate-500 tracking-wider text-[10px]">Rate</th>
                      <th className="text-center py-3 px-4 font-black uppercase text-slate-500 tracking-wider text-[10px]">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {analyticsData.revisionConsistencyChart.map((row: any, i: number) => {
                      const rate = row.scheduled > 0 ? Math.round((row.completed / row.scheduled) * 100) : 0;
                      return (
                        <tr key={i} className="border-b border-slate-50 hover:bg-slate-50/50">
                          <td className="py-3 px-4 font-bold text-slate-700">{row.subject}</td>
                          <td className="py-3 px-4 text-center font-mono font-bold text-slate-500">{row.scheduled}</td>
                          <td className="py-3 px-4 text-center font-mono font-bold text-success">{row.completed}</td>
                          <td className="py-3 px-4 text-center font-mono font-bold text-primary">{rate}%</td>
                          <td className="py-3 px-4 text-center">
                            <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded border ${
                              rate >= 80
                                ? 'bg-success/10 text-success border-success/20'
                                : rate >= 50
                                ? 'bg-warning/10 text-warning border-warning/20'
                                : 'bg-critical/10 text-critical border-critical/20'
                            }`}>
                              {rate >= 80 ? 'Strong' : rate >= 50 ? 'Moderate' : 'Weak'}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Section 5: Study Consistency Heatmap */}
          <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200 print:break-before-page">
            <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
              <Calendar className="w-5 h-5 text-primary" />
              <span>6-Month Activity Heatmap</span>
            </h3>
            <Heatmap data={stats?.heatmapData || {}} />
          </div>

          {/* Section 6: Smart Insights */}
          {analyticsData?.insights && analyticsData.insights.length > 0 && (
            <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm print:shadow-none print:border-slate-200">
              <h3 className="font-hanken font-bold text-base text-slate-800 border-b border-border pb-3 mb-5 flex items-center space-x-2">
                <CheckCircle className="w-5 h-5 text-success" />
                <span>Automated Performance Insights</span>
              </h3>

              <div className="space-y-3">
                {analyticsData.insights.map((insight: string, idx: number) => (
                  <div
                    key={idx}
                    className="flex items-start space-x-3 text-xs text-slate-600 leading-relaxed font-semibold bg-slate-50 border border-slate-100 rounded-xl p-4 print:bg-white"
                  >
                    <span className="w-5 h-5 rounded-full bg-primary/10 text-primary flex items-center justify-center font-mono font-bold flex-shrink-0 mt-0.5 text-[10px]">
                      {idx + 1}
                    </span>
                    <span dangerouslySetInnerHTML={{ __html: insight }} />
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Report Footer (print) */}
          <div className="hidden print:block border-t-2 border-primary pt-4 mt-8 text-center">
            <p className="text-[10px] text-slate-400 font-semibold">
              StudyPulse Academic Report • ICSE Class 10 • Auto-generated on {todayFormatted}
            </p>
            <p className="text-[9px] text-slate-300 font-medium mt-1">
              This report is computer-generated and does not require a manual signature.
            </p>
          </div>

        </div>
      </div>
    </LayoutWrapper>
  );
}
